version: 2
jobs:
  build:
    machine: true

    dependencies:
      override:
        - curl -L -o google-chrome.deb https://s3.amazonaws.com/circle-downloads/google-chrome-stable_current_amd64_47.0.2526.73-1.deb
        - sudo dpkg -i google-chrome.deb
        - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        - rm google-chrome.deb

    steps:
      - checkout

      - run: |
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install dpkg
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb

      - run: |
          source $NVM_DIR/nvm.sh
          nvm install v10.16.0

          npm install
          npm run install-webdriver-ts
          npm start &
          npm run build -- --check
