[package]
name = "js-framework-benchmark-yew"
version = "1.0.0"
authors = ["Isamu Mogi <isamu@leafytree.jp>"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
panic = "abort"

[dependencies]
byteorder = { version = "1.2.4", features = [ "i128" ] }
rand = { version = "0.5.4" }
js-sys = "0.3.40"
yew = { git = "https://github.com/yewstack/yew.git", rev = "a6295bf8fdbaf4395f3c14f119864dfc83f84204" }
wasm-bindgen = "0.2.63"
